# Generated by Django 5.1.3 on 2024-11-18 20:55

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0002_articlealbum_articlearticle_articlebook_articlecamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('embed', 12), ('quote', 13), ('imageblock', 10), ('videoblock', 16), ('documentblock', 19)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('', 'Select a heading size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 1)]], {}), 3: ('encyclopedia.blocks.ArticleTextBlock', (), {}), 4: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 5: ('wagtail.images.blocks.ImageBlock', [], {}), 6: ('wagtail.blocks.TextBlock', (), {'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'required': False}), 8: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 9: ('wagtail.blocks.URLBlock', (), {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('image', 5), ('caption', 6), ('caption2', 6), ('courtesy', 7), ('creative_commons', 8), ('ext_url', 9)]], {}), 11: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Insert a URL to embed. For example, https://youtu.be/sWqDIZxO-nU', 'icon': 'media'}), 12: ('wagtail.blocks.StreamBlock', [[('heading_block', 2), ('paragraph_block', 4), ('image_block', 10), ('embed_block', 11)]], {}), 13: ('wagtail.blocks.StructBlock', [[('quotation', 4), ('attribution', 7)]], {}), 14: ('wagtailmedia.blocks.VideoChooserBlock', (), {'required': False}), 15: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': False}), 16: ('wagtail.blocks.StructBlock', [[('video', 14), ('transcript', 15), ('caption', 6), ('caption2', 6), ('courtesy', 7), ('creative_commons', 8)]], {}), 17: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': True}), 18: ('wagtail.blocks.StructBlock', [[('image', 5), ('caption', 6), ('caption2', 6), ('courtesy', 7), ('creative_commons', 8), ('ext_url', 9)]], {'required': False}), 19: ('wagtail.blocks.StructBlock', [[('document', 17), ('display', 18), ('caption', 6), ('caption2', 6), ('courtesy', 7), ('creative_commons', 8), ('ext_url', 9)]], {})}, help_text='BODY HELP TEXT GOES HERE.'),
        ),
    ]
