# Generated by Django 5.1.6 on 2025-03-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0003_alter_article_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediawikiWagtail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediawiki_url', models.CharField(help_text='MediaWiki title URL', max_length=255)),
                ('wagtail_slug', models.CharField(help_text='Wagtail title slug', max_length=255)),
            ],
        ),
    ]
