# Generated by Django 5.2.1 on 2025-06-24 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0004_mediawikiwagtail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediawikiwagtail',
            options={'verbose_name': 'Mediawiki-Wagtail', 'verbose_name_plural': 'Mediawiki-Wagtail'},
        ),
    ]
