# Generated by Django 5.2.1 on 2025-07-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0005_alter_mediawikiwagtail_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title_sort',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
