# Generated by Django 5.2.1 on 2025-07-31 00:09

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0006_article_title_sort'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['title_sort', 'title'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=wagtail.fields.StreamField([('paragraph', 0)], block_lookup={0: ('encyclopedia.blocks.ArticleTextBlock', (), {})}, help_text='Description should only be one paragraph.'),
        ),
    ]
