# Generated by Django 5.2.1 on 2025-08-01 17:43

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0007_alter_article_options_alter_article_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='footnotes',
            field=wagtail.fields.RichTextField(blank=True, editable=False, null=True),
        ),
    ]
