# Generated by Django 5.2.6 on 2025-10-02 17:45

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0008_alter_article_footnotes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='signature_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('embed', 12), ('quote', 13), ('imageblock', 10), ('videoblock', 16), ('documentblock', 19)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('', 'Select a heading size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 1)]], {}), 3: ('encyclopedia.blocks.ArticleTextBlock', (), {}), 4: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 5: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 6: ('wagtail.images.blocks.ImageBlock', [], {}), 7: ('wagtail.blocks.TextBlock', (), {'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'required': False}), 9: ('wagtail.blocks.URLBlock', (), {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('signature', 5), ('image', 6), ('caption', 7), ('caption2', 7), ('courtesy', 8), ('creative_commons', 5), ('ext_url', 9)]], {}), 11: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Insert a URL to embed. For example, https://youtu.be/sWqDIZxO-nU', 'icon': 'media'}), 12: ('wagtail.blocks.StreamBlock', [[('heading_block', 2), ('paragraph_block', 4), ('image_block', 10), ('embed_block', 11)]], {}), 13: ('wagtail.blocks.StructBlock', [[('quotation', 4), ('attribution', 8)]], {}), 14: ('wagtailmedia.blocks.VideoChooserBlock', (), {'required': False}), 15: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': False}), 16: ('wagtail.blocks.StructBlock', [[('video', 14), ('transcript', 15), ('caption', 7), ('caption2', 7), ('courtesy', 8), ('creative_commons', 5)]], {}), 17: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': True}), 18: ('wagtail.blocks.StructBlock', [[('signature', 5), ('image', 6), ('caption', 7), ('caption2', 7), ('courtesy', 8), ('creative_commons', 5), ('ext_url', 9)]], {'required': False}), 19: ('wagtail.blocks.StructBlock', [[('document', 17), ('display', 18), ('caption', 7), ('caption2', 7), ('courtesy', 8), ('creative_commons', 5), ('ext_url', 9)]], {})}, help_text='BODY HELP TEXT GOES HERE.'),
        ),
    ]
