# Generated by Django 6.0 on 2025-12-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0010_alter_article_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='mw_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
