# Generated by Django 6.0.3 on 2026-03-18 19:17

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0011_article_mw_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['title_sort', 'title'], 'verbose_name': 'Basic Article', 'verbose_name_plural': 'Basic Articles'},
        ),
        migrations.AlterModelOptions(
            name='articlearticle',
            options={'verbose_name': 'Article/essay/story/etc', 'verbose_name_plural': 'Articles/essays/stories/etc'},
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('embed', 12), ('quote', 13), ('imageblock', 10), ('videoblock', 16), ('documentblock', 18)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('', 'Select a heading size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 1)]], {}), 3: ('encyclopedia.blocks.ArticleTextBlock', (), {}), 4: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 5: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 6: ('wagtail.images.blocks.ImageBlock', [], {}), 7: ('wagtail.blocks.TextBlock', (), {'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'required': False}), 9: ('wagtail.blocks.URLBlock', (), {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('signature', 5), ('image', 6), ('caption', 7), ('caption2', 7), ('courtesy', 8), ('creative_commons', 5), ('ext_url', 9)]], {}), 11: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Insert a URL to embed. For example, https://youtu.be/sWqDIZxO-nU', 'icon': 'media'}), 12: ('wagtail.blocks.StreamBlock', [[('heading_block', 2), ('paragraph_block', 4), ('image_block', 10), ('embed_block', 11)]], {}), 13: ('wagtail.blocks.StructBlock', [[('quotation', 4), ('attribution', 8)]], {}), 14: ('wagtailmedia.blocks.VideoChooserBlock', (), {'required': False}), 15: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': False}), 16: ('wagtail.blocks.StructBlock', [[('video', 14), ('display', 6), ('transcript', 15), ('caption', 7), ('caption2', 7), ('courtesy', 8), ('creative_commons', 5)]], {}), 17: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': True}), 18: ('wagtail.blocks.StructBlock', [[('document', 17), ('display', 6), ('caption', 7), ('caption2', 7), ('courtesy', 8), ('creative_commons', 5), ('ext_url', 9)]], {})}, help_text='The main body of the article.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=wagtail.fields.StreamField([('paragraph', 0)], block_lookup={0: ('encyclopedia.blocks.ArticleTextBlock', (), {})}, help_text='Single paragraph that will be shown in lists, search results, etc.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_sort',
            field=models.CharField(blank=True, help_text='Stripped-down title used for ordering articles in lists. Stop words removed, etc.', max_length=255, null=True),
        ),
    ]
