# Generated by Django 6.0.3 on 2026-04-18 00:21

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0012_alter_article_options_alter_articlearticle_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='related_articles',
            field=wagtail.fields.StreamField([('paragraph', 0)], blank=True, block_lookup={0: ('encyclopedia.blocks.ArticleTextBlock', (), {})}, help_text='List of related articles in the Encyclopedia.', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='related_json',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
