# Generated by Django 6.0.3 on 2026-06-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0014_articletopic_article_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlenewspaper',
            name='peak_date',
        ),
        migrations.AddField(
            model_name='articleexhibition',
            name='name',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
