# Generated by Django 6.0.3 on 2026-07-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0015_remove_articlenewspaper_peak_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlearticle',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AddField(
            model_name='article',
            name='mw_page_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
