# Generated by Django 6.0.3 on 2026-07-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0016_alter_articlearticle_options_article_mw_page_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='mw_first_published_revid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='mw_first_published_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='mw_lastmod_revid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='mw_lastmod_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
