# Generated by Django 6.0.3 on 2026-08-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0017_article_mw_first_published_revid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='mw_migration_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
