services:
  encyc-tng:
    build:
      context: .
    command: make runserver
    ports:
      - 8082:8082
    volumes:
      - ./static_src:/opt/encyc-tng/static_src
      - ./encyclopedia:/opt/encyc-tng/encyclopedia
      - ./encyctng:/opt/encyc-tng/encyctng
      - ./patterns:/opt/encyc-tng/patterns
      - ./templates:/opt/encyc-tng/templates
      - ./conf/encyctng.cfg:/etc/encyc/core.cfg
      - ./conf/encyctng-local-docker.cfg:/etc/encyc/core-local.cfg
    depends_on:
      - db
      - redis

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: encyctng
      POSTGRES_USER: encyctng

  redis:
    image: redis:6-alpine
    expose:
      - 6379
