# Maps Mediawiki databoxes to encyc-tng classes
# SEE ALSO Template:RGDatabox-Core
DATABOXES = {

    'databox-Albums': {
        'class': 'ArticleAlbum',
        'templatetag': 'encyclopedia/databox-album.html',
        'fields': [
            {'mw': 'Name', 'tng': 'album_title', 'label': 'Name'},
            {'mw': 'Artist', 'tng': 'artist', 'label': 'Artist'},
            {'mw': 'Type', 'tng': 'album_type', 'label': 'Type'},
            {'mw': 'Recorded', 'tng': 'recorded', 'label': 'Recorded'},
            {'mw': 'Released', 'tng': 'released', 'label': 'Released'},
            {'mw': 'Genre', 'tng': 'genre', 'label': 'Genre'},
            {'mw': 'Length', 'tng': 'length', 'label': 'Length'},
            {'mw': 'Label', 'tng': 'label', 'label': 'Label'},
            {'mw': 'Producer', 'tng': 'producer', 'label': 'Producer'},
            {'mw': 'Website', 'tng': 'official_url', 'label': 'Official Web Site'},
            {'mw': 'MBLink', 'tng': 'musicbrainz_url', 'label': 'MusicBrainz Link'},
            {'mw': 'DCLink', 'tng': 'discogs_url', 'label': 'Discogs Link'},
        ],
    },

    'databox-Articles': {
        'class': 'ArticleArticle',
        'templatetag': 'encyclopedia/databox-article.html',
        'fields': [
            {'mw': 'Author', 'tng': 'author', 'label': 'Author'},
            {'mw': 'Title', 'tng': 'article_title', 'label': 'Article title'},
            {'mw': 'PubName', 'tng': 'pubname', 'label': 'Publication name'},
            {'mw': 'PubDate', 'tng': 'pubdate', 'label': 'Date of publication'},
            {'mw': 'PubDetails', 'tng': 'pubdetails', 'label': 'Publication details'},
            {'mw': 'DOI', 'tng': 'doi_url', 'label': 'Digital Object Identifier'},
            {'mw': 'Website', 'tng': 'url', 'label': 'Web link'},
        ],
    },

    'databox-Books': {
        'class': 'ArticleBook',
        'templatetag': 'encyclopedia/databox-book.html',
        'fields': [
            {'mw': 'Title',           'tng': 'book_title',       'label': 'Title'},
            {'mw': 'Author',          'tng': 'author',           'label': 'Author'},
            {'mw': 'Illustrator',     'tng': 'illustrator',      'label': 'Illustrator'},
            {'mw': 'OrigTitle',       'tng': 'title_orig',       'label': 'Original Title'},
            {'mw': 'Country',         'tng': 'country',          'label': 'Country'},
            {'mw': 'Language',        'tng': 'language',         'label': 'Language'},
            {'mw': 'Series',          'tng': 'series',           'label': 'Series'},
            {'mw': 'Genre',           'tng': 'genre',            'label': 'Genre'},
            {'mw': 'Publisher',       'tng': 'publisher',        'label': 'Publisher'},
            {'mw': 'PubDate',         'tng': 'pubdate',          'label': 'Publish Date'},
            {'mw': 'CurrentPublisher','tng': 'publisher_current','label': 'Current Publisher'},
            {'mw': 'CurrentPubDate',  'tng': 'pubdate_current',  'label': 'Current Publish Date'},
            {'mw': 'MediaType',       'tng': 'media_type',       'label': 'Media Type'},
            {'mw': 'Pages',           'tng': 'pages',            'label': 'Pages'},
            {'mw': 'Awards',          'tng': 'awards',           'label': 'Awards'},
            {'mw': 'ISBN',            'tng': 'isbn',             'label': 'ISBN'},
            {'mw': 'WorldCatLink',    'tng': 'worldcat_url',     'label': 'WorldCat Link'},
        ],
    },

    'databox-Camps': {
        'class': 'ArticleCamp',
        'templatetag': 'encyclopedia/databox-camp.html',
        'fields': [
            {'mw': 'SoSUID', 'tng': 'sos_uid', 'label': 'Sites of Shame UID'},
            {'mw': 'DenshoName', 'tng': 'densho_name', 'label': 'Densho Name'},
            {'mw': 'USGName', 'tng': 'usg_name', 'label': 'USG Name'},
            {'mw': 'Type', 'tng': 'facility_type', 'label': 'Type'},
            {'mw': 'AdminAgency', 'tng': 'admin_agency', 'label': 'Admin Agency'},
            {'mw': 'DateOpened', 'tng': 'date_opened', 'label': 'Date Opened'},
            {'mw': 'DateClosed', 'tng': 'date_closed', 'label': 'Date Closed'},
            {'mw': 'LocationName', 'tng': 'location_name', 'label': 'Location Name'},
            {'mw': 'CityName', 'tng': 'city_name', 'label': 'City Name'},
            {'mw': 'StateName', 'tng': 'state_name', 'label': 'State Name'},
            {'mw': 'Description', 'tng': 'facility_descr', 'label': 'Description'},
            {'mw': 'GISLat', 'tng': 'gis_lat', 'label': 'GIS Lat'},
            {'mw': 'GISLng', 'tng': 'gis_long', 'label': 'GIS Lng'},
            {'mw': 'GISTGNId', 'tng': 'gis_tgn_id', 'label': 'GIS TGN ID'},
            {'mw': 'CurrentDisposition', 'tng': 'current_disposition', 'label': 'Current Disposition'},
            {'mw': 'PopulationDescription', 'tng': 'population_descr', 'label': 'Population Description'},
            {'mw': 'ExitDestination', 'tng': 'exit_destination', 'label': 'Exit Destination'},
            {'mw': 'PeakPopulation', 'tng': 'peak_population', 'label': 'Peak Population'},
            {'mw': 'PeakDate', 'tng': 'peak_date', 'label': 'Peak Date'},
            {'mw': 'NPSMoreInfoResourceLink', 'tng': 'nps_link', 'label': 'NPS More Info Resource Link'},
            {'mw': 'OfficialResourceLink', 'tng': 'official_link', 'label': 'Official Resource Link'},
        ],
    },

    #'databox-Chapters': {},

    'databox-Exhibitions': {
        'class': 'ArticleExhibition',
        'templatetag': 'encyclopedia/databox-exhibition.html',
        'fields': [
            {'mw': 'FirstDate', 'tng': 'first_date', 'label': 'Date of first opening'},
            {'mw': 'FinalDate', 'tng': 'final_date', 'label': 'Date of final opening'},
            {'mw': 'Location', 'tng': 'location', 'label': 'Location'},
            {'mw': 'Organization', 'tng': 'organization', 'label': 'Organization'},
            {'mw': 'Curator', 'tng': 'curator', 'label': 'Curator'},
            {'mw': 'Producer', 'tng': 'producer', 'label': 'Producer'},
            {'mw': 'KeyStaff', 'tng': 'key_staff', 'label': 'Key Staff'},
            {'mw': 'Website', 'tng': 'url', 'label': 'Official Website'},
        ],
    },

    'databox-Films': {
        'class': 'ArticleFilm',
        'templatetag': 'encyclopedia/databox-film.html',
        'fields': [
            {'mw': 'Title', 'tng': 'film_title', 'label': 'Title'},
            {'mw': 'Date', 'tng': 'film_date', 'label': 'Date'},
            {'mw': 'Genre', 'tng': 'genre', 'label': 'Genre'},
            {'mw': 'Released', 'tng': 'released', 'label': 'Released'},
            {'mw': 'Director', 'tng': 'director', 'label': 'Director'},
            {'mw': 'Producer', 'tng': 'producer', 'label': 'Producer'},
            {'mw': 'Writer', 'tng': 'writer', 'label': 'Writer'},
            {'mw': 'Screenplay', 'tng': 'screenplay', 'label': 'Screenplay'},
            {'mw': 'Story', 'tng': 'story', 'label': 'Story'},
            {'mw': 'BasedOn', 'tng': 'based_on', 'label': 'Based On'},
            {'mw': 'Narrator', 'tng': 'narrator', 'label': 'Narrator'},
            {'mw': 'Starring', 'tng': 'starring', 'label': 'Starring'},
            {'mw': 'Music', 'tng': 'music', 'label': 'Music'},
            {'mw': 'Cinematography', 'tng': 'cinematography', 'label': 'Cinematography'},
            {'mw': 'Editing', 'tng': 'editing', 'label': 'Editing'},
            {'mw': 'Studio', 'tng': 'studio', 'label': 'Studio'},
            {'mw': 'Distributor', 'tng': 'distributor', 'label': 'Distributor'},
            {'mw': 'Runtime', 'tng': 'runtime', 'label': 'Runtime'},
            {'mw': 'Country', 'tng': 'country', 'label': 'Country'},
            {'mw': 'Language', 'tng': 'language', 'label': 'Language'},
            {'mw': 'Budget', 'tng': 'budget', 'label': 'Budget'},
            {'mw': 'Gross', 'tng': 'gross', 'label': 'Gross'},
            {'mw': 'IMDBLink', 'tng': 'imdb_url', 'label': 'IMDB'},
            {'mw': 'TrailerLink', 'tng': 'trailer_url', 'label': 'Trailer'},
        ],
    },

    'databox-Magazines': {
        'class': 'ArticleMagazine',
        'templatetag': 'encyclopedia/databox-magazine.html',
        'fields': [
            {'mw': 'Name', 'tng': 'magazine_name', 'label': 'Name'},
            {'mw': 'YearFounded', 'tng': 'year_founded', 'label': 'Year Founded'},
            {'mw': 'FirstDate', 'tng': 'first_date', 'label': 'First issue date'},
            {'mw': 'FinalDate', 'tng': 'final_date', 'label': 'Final issue date'},
            {'mw': 'FinalIssue', 'tng': 'final_issue', 'label': 'Final Issue'},
            {'mw': 'Frequency', 'tng': 'frequency', 'label': 'Frequency'},
            {'mw': 'Editor', 'tng': 'editor', 'label': 'Editor'},
            {'mw': 'FormerEditors', 'tng': 'former_editors', 'label': 'Former Editors'},
            {'mw': 'StaffWriters', 'tng': 'staff_writers', 'label': 'Staff Writers'},
            {'mw': 'Photographers', 'tng': 'photographers', 'label': 'Photographers'},
            {'mw': 'Founder', 'tng': 'founder', 'label': 'Founder'},
            {'mw': 'Publisher', 'tng': 'publisher', 'label': 'Publisher'},
            {'mw': 'Company', 'tng': 'company', 'label': 'Company'},
            {'mw': 'Circulation', 'tng': 'circulation', 'label': 'Circulation'},
            {'mw': 'Country', 'tng': 'country', 'label': 'Country'},
            {'mw': 'Language', 'tng': 'language', 'label': 'Language'},
            {'mw': 'ISSN', 'tng': 'issn', 'label': 'ISSN'},
            {'mw': 'WorldCatLink', 'tng': 'worldcat_url', 'label': 'WorldCat Link'},
        ],
    },

    'databox-Newspapers': {
        'class': 'ArticleNewspaper',
        'templatetag': 'encyclopedia/databox-newspaper.html',
        'fields': [
            {'mw': 'PublicationName', 'tng': 'publication_name', 'label': 'Publication Name'},
            {'mw': 'CampArticle', 'tng': 'camp_article', 'label': 'Camp Article'},
            {'mw': 'PublicationStartDate', 'tng': 'publication_start_date', 'label': 'Publication Start Date'},
            {'mw': 'PublicationEndDate', 'tng': 'publication_end_date', 'label': 'Publication End Date'},
            {'mw': 'PredecessorPub', 'tng': 'predecessor_pub', 'label': 'Predecessor Pub'},
            {'mw': 'SuccessorPub', 'tng': 'successor_pub', 'label': 'Successor Pub'},
            {'mw': 'ModeOfProduction', 'tng': 'mode_of_production', 'label': 'Mode Of Production'},
            {'mw': 'Staff', 'tng': 'staff', 'label': 'Staff'},
        ],
    },

    'databox-People': {
        'class': 'ArticlePerson',
        'templatetag': 'encyclopedia/databox-person.html',
        'fields': [
            {'mw': 'FirstName',        'tng': 'first_name',     'label': 'First Name'},
            {'mw': 'LastName',         'tng': 'last_name',      'label': 'Last Name'},
            {'mw': 'DisplayName',      'tng': 'display_name',   'label': 'Display Name'},
            {'mw': 'BirthDate',        'tng': 'birth_date',     'label': 'Birth Date'},
            {'mw': 'DeathDate',        'tng': 'death_date',     'label': 'Death Date'},
            {'mw': 'BirthLocation',    'tng': 'birth_location', 'label': 'Birth Location'},
            {'mw': 'Gender',           'tng': 'gender',         'label': 'Gender'},
            {'mw': 'Ethnicity',        'tng': 'ethnicity',      'label': 'Ethnicity'},
            {'mw': 'GenerationIdentifier', 'tng': 'generation', 'label': 'Generation Identifier'},
            {'mw': 'Nationality',      'tng': 'nationality',    'label': 'Nationality'},
            {'mw': 'ExternalResourceLink', 'tng': 'external_url', 'label': 'External Resource Link'},
            {'mw': 'PrimaryGeography', 'tng': 'primary_geography', 'label': 'Primary Geography'},
            {'mw': 'Religion',         'tng': 'religion',       'label': 'Religion'},
        ],
    },

    'databox-Plays': {
        'class': 'ArticlePlay',
        'templatetag': 'encyclopedia/databox-play.html',
        'fields': [
            {'mw': 'Name', 'tng': 'play_name', 'label': 'Name'},
            {'mw': 'FirstDate', 'tng': 'first_data', 'label': 'Date of first production'},
            {'mw': 'FinalDate', 'tng': 'final_date', 'label': 'Date of final production'},
            {'mw': 'Location', 'tng': 'location', 'label': 'Location'},
            {'mw': 'Writer', 'tng': 'writer', 'label': 'Writer'},
            {'mw': 'Director', 'tng': 'director', 'label': 'Director'},
            {'mw': 'Producer', 'tng': 'producer', 'label': 'Producer'},
            {'mw': 'Creative', 'tng': 'creative', 'label': 'Creative'},
            {'mw': 'Technical', 'tng': 'technical', 'label': 'Technical'},
            {'mw': 'Characters', 'tng': 'characters', 'label': 'Characters'},
            {'mw': 'Website', 'tng': 'official_url', 'label': 'Official Website'},
            {'mw': 'PlaybillLink', 'tng': 'playbill_url', 'label': 'Playbill Link'},
            {'mw': 'IBDBID', 'tng': 'ibdb_id', 'label': 'Internet Broadway Database ID'},
            {'mw': 'IODBID', 'tng': 'iodb_id', 'label': 'Lortel Archives Internet Off-Broadway database ID'},
            {'mw': 'TheatricaliaID', 'tng': 'theatricalia_id', 'label': 'Theatricalia ID'},
            {'mw': 'Publisher', 'tng': 'publisher', 'label': 'Original Publisher'},
            {'mw': 'PubDate', 'tng': 'pubdate', 'label': 'Original Publication Date'},
            {'mw': 'CurrentPublisher', 'tng': 'current_publisher', 'label': 'Current Publisher'},
            {'mw': 'CurrentPubDate', 'tng': 'current_pubdate', 'label': 'Current Publication Date'},
        ],
    },

    #'databox-Songs': {},
    #'databox-Test': {},

    'databox-Websites': {
        'class': 'ArticleWebsite',
        'templatetag': 'encyclopedia/databox-website.html',
        'fields': [
            {'mw': 'Type', 'tng': 'website_type', 'label': 'Type'},
            {'mw': 'URL', 'tng': 'url', 'label': 'URL'},
            {'mw': 'Title', 'tng': 'website_title', 'label': 'Title'},
            {'mw': 'Creator', 'tng': 'creator', 'label': 'Creator'},
            {'mw': 'Active', 'tng': 'active', 'label': 'Active'},
            {'mw': 'HasBlog', 'tng': 'has_blog', 'label': 'Has Blog'},
            {'mw': 'PrimarySources', 'tng': 'primary_sources', 'label': 'Available Primary Sources'},
        ],
    },

}

ARTICLE_CLASS_DATABOX = {val['class']: key for key,val in DATABOXES.items()}

ARTICLE_CLASS_FIELDNAMES = {
    databox['class']: [field['tng'] for field in databox['fields']]
    for key,databox in DATABOXES.items()
}
