# Generated by Django 6.0 on 2026-02-10 23:13

import django_extensions.db.fields
import sources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('published', models.BooleanField(default=False)),
                ('densho_id', models.CharField(help_text='Valid DDR object ID', max_length=255)),
                ('headword', models.CharField(help_text="Article title in editors' wiki", max_length=255)),
                ('encyclopedia_id', models.CharField(help_text='Valid DDR or Densho ID (must be unique)', max_length=255, unique=True)),
                ('caption', models.TextField(blank=True, help_text='Contents of this field will be visible on the article page, in lightboxes, and on the Primary Source detail page.', null=True)),
                ('caption_extended', models.TextField(blank=True, help_text='Contents of this field will only be visible on the Primary Source detail page.', null=True, verbose_name='Caption (Extended)')),
                ('courtesy', models.TextField(blank=True, null=True)),
                ('institution_id', models.CharField(blank=True, max_length=255, null=True)),
                ('collection_name', models.CharField(blank=True, max_length=255, null=True)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('creative_commons', models.BooleanField(default=False)),
                ('original', models.FileField(blank=True, help_text='Full-size file from which thumbnails, keyframes, etc are derived', null=True, upload_to=sources.models.get_object_upload_path, verbose_name='Original')),
                ('original_size', models.IntegerField(blank=True, null=True)),
                ('streaming_url', models.CharField(blank=True, help_text='URL for streaming media (video, audio). Must be a full URL, including domain name.', max_length=255, null=True, verbose_name='Streaming URL')),
                ('transcript', models.FileField(blank=True, null=True, upload_to=sources.models.get_object_upload_path)),
                ('display', models.ImageField(blank=True, help_text='Image file used in lists and other interstitial pages', null=True, upload_to=sources.models.get_object_upload_path)),
                ('update_display', models.BooleanField(default=False, help_text="Refresh copy of display file in MediaWiki (click this if the image in MediaWiki doesn't change.", verbose_name='Refresh display')),
                ('media_format', models.CharField(choices=[('image', 'photo'), ('document', 'document'), ('video', 'VH')], max_length=32, verbose_name='Format')),
                ('aspect_ratio', models.CharField(blank=True, choices=[('hd', 'HD'), ('sd', 'SD')], max_length=32, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Primary Source',
                'verbose_name_plural': 'Primary Sources',
            },
        ),
    ]
