# Generated by Django 5.2.1 on 2025-07-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editors', '0002_author_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
