# Generated by Django 5.2.6 on 2025-10-31 17:03

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepagecarouselindexpage'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageCarousel',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('publish_date', models.DateTimeField()),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('images', wagtail.fields.StreamField([('imageblock', 5)], blank=True, block_lookup={0: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 1: ('wagtail.images.blocks.ImageBlock', [], {}), 2: ('wagtail.blocks.TextBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('signature', 0), ('image', 1), ('caption', 2), ('caption2', 2), ('courtesy', 3), ('creative_commons', 0), ('ext_url', 4)]], {})}, help_text='Add one or more Image objects.')),
            ],
            options={
                'verbose_name': 'Home Page Carousel',
                'verbose_name_plural': 'Home Page Carousels',
                'ordering': ['title'],
            },
            bases=('wagtailcore.page',),
        ),
    ]
