# Generated by Django 6.0 on 2026-01-08 17:34

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepagecarousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecarousel',
            name='images',
            field=wagtail.fields.StreamField([('imageblock', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageBlock', [], {}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'required': False}), 3: ('wagtail.blocks.TextBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 0), ('article_title', 1), ('article_url', 2), ('description', 3)]], {})}, help_text='Add one or more Image objects.'),
        ),
    ]
