"""
Django settings for encyctng project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import configparser
from datetime import date, datetime
from os import environ
from pathlib import Path
import subprocess
import sys
import zoneinfo

# Build paths inside the project like this: BASE_DIR / PATH
PROJECT_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = PROJECT_DIR.parent

VERSION_PATH = BASE_DIR / 'VERSION'
with VERSION_PATH.open('r') as f:
    VERSION = f.read().strip()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# User-configurable settings are located in the following files.
# Files appearing *later* in the list override earlier files.
CONFIG_FILES = [
    '/etc/encyc/encyctng.cfg',
    '/etc/encyc/encyctng-local.cfg'
]
ENCYCTNG_EDITORS = environ.get('ENCYCTNG_EDITORS')
if ENCYCTNG_EDITORS and ENCYCTNG_EDITORS == 'true':
    CONFIG_FILES += ['/etc/encyc/encyctng-editors.cfg']
config = configparser.ConfigParser()
configs_read = config.read(CONFIG_FILES)
if not configs_read:
    print(f'Cannot read config files! {CONFIG_FILES}')
    sys.exit(1)

LOG_LEVEL = config.get('django', 'log_level')
LOG_FILE = config.get('django', 'log_file')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config.getboolean('django', 'debug')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config.get('django', 'secret_key')

ALLOWED_HOSTS = [
    host.strip()
    for host in config.get('django', 'allowed_hosts').strip().split(',')
    if host.strip()
]

CSRF_TRUSTED_ORIGINS = [
    host.strip()
    for host in config.get('django', 'csrf_origins').strip().split(',')
    if host.strip()
]

CSRF_COOKIE_SECURE = config.getboolean('django', 'csrf_cookie_secure')
SESSION_COOKIE_SECURE = config.getboolean('django', 'session_cookie_secure')

APPLICATION_ENVIRONMENT = config.get('encyctng', 'environment')


# Django

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.messages',
    'django.contrib.postgres',
    'django.contrib.sessions',
    'django.contrib.sitemaps',
    'django.contrib.staticfiles',
    'modelcluster',
    'ninja',
    'taggit',
    'wagtail',
    'wagtail.admin',
    'wagtail.contrib.forms',
    'wagtail.contrib.redirects',
    'wagtail.contrib.table_block',
    'wagtail.documents',
    'wagtail.embeds',
    'encyclopedia.apps.CustomImagesAppConfig',  #'wagtail.images',
    'wagtail.search',
    'wagtail.sites',
    'wagtail.snippets',
    'wagtail.users',
    'wagtailmedia',
    #
    'home',
    'editors',
    'encyclopedia',
    'info',
    'search',
    'sources',
    'styleguide',
]
if APPLICATION_ENVIRONMENT == 'development':
    INSTALLED_APPS += ['pattern_library']

MIDDLEWARE = [
    'log_request_id.middleware.RequestIDMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'encyclopedia.middleware.ArticleMiddleware',
    'wagtail.contrib.redirects.middleware.RedirectMiddleware',
]

ROOT_URLCONF = 'encyctng.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            PROJECT_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'encyctng.context_processors.sitewide',
            ],
            'builtins': [
                'pattern_library.loader_tags',
            ],
        },
    },
]
if DEBUG:
    TEMPLATES[0]['OPTIONS']['context_processors'].insert(
        0, 'django.template.context_processors.debug'
    )

WSGI_APPLICATION = 'encyctng.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        "ENGINE": config.get('django', 'database_engine'),
        'NAME': config.get('django', 'database_name'),
        'HOST': config.get('django', 'database_host'),
        'PORT': config.get('django', 'database_port'),
        'USER': config.get('django', 'database_username'),
        'PASSWORD': config.get('django', 'database_password'),
    }
}

REDIS_HOST = config.get('django', 'redis_host')
REDIS_PORT = config.get('django', 'redis_port')
REDIS_DB_CACHE = '10'

CACHES = {
    "default": {
        #'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB_CACHE}",
    }
}

CACHE_TIMEOUT = config.getint('django', 'cache_timeout')
CACHE_TIMEOUT_LONG = config.getint('django', 'cache_timeout_long')

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

SESSION_ENGINE = 'django.contrib.sessions.backends.cache'

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
USE_I18N = True

#TIME_ZONE = 'UTC'
TIME_ZONE = 'America/Los_Angeles'
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# Points to STATIC_ROOT
STATIC_URL = '/static/'

# Directory from which Nginx will serve static files
STATIC_ROOT = config.get('django', 'static_root')

# Directories where collectstatic will look for static files
STATICFILES_DIRS = [
    PROJECT_DIR / 'static_compiled',
    '/opt/encyc-tng-assets/static',
]

# Media files (uploads)

MEDIA_ROOT = config.get('django', 'media_root')
MEDIA_URL = '/media/'

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# Logging and error reporting

LOG_REQUEST_ID_HEADER = "HTTP_X_REQUEST_ID"
GENERATE_REQUEST_ID_IF_NOT_IN_HEADER = True

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    'formatters': {
        'verbose': {
            'format': '%(asctime)s %(request_id)s %(levelname)-8s [%(module)s.%(funcName)s]  %(message)s'
        },
        'simple': {
            'format': '%(asctime)s %(request_id)s %(levelname)-8s %(message)s'
        },
    },
    'filters': {
        'request_id': {
            '()': 'log_request_id.filters.RequestIDFilter'
        },
        # only log when settings.DEBUG == False
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse'
        },
    },
    "handlers": {
        'null': {
            'level': 'DEBUG',
            'class': 'logging.NullHandler',
        },
        'console':{
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'filters': ['request_id'],
            'formatter': 'simple',
        },
        'file': {
            'level': LOG_LEVEL,
            'class': 'logging.handlers.WatchedFileHandler',
            'filename': '/var/log/encyc/encyctng.log',
            'filters': ['request_id'],
            'formatter': 'verbose',
        },
    },
    "loggers": {
        "django": {
            "handlers": ["file"],
            "level": LOG_LEVEL,
            "propagate": True,
        },
    },
    'root': {
        'level': LOG_LEVEL,
        'handlers': ['file'],
    },
}


# Wagtail settings

WAGTAIL_SITE_NAME = 'Densho Encyclopedia'

# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
WAGTAILADMIN_BASE_URL = config.get('wagtail', 'base_url')

# Search
# https://docs.wagtail.org/en/stable/topics/search/backends.html
WAGTAILSEARCH_BACKENDS = {
    'default': {
        'BACKEND': 'wagtail.search.backends.database',
    }
}

# Disable commenting
WAGTAILADMIN_COMMENTS_ENABLED = False

# Limit slugs to ASCII characters
WAGTAIL_ALLOW_UNICODE_SLUGS = False

# disable autosave for now
WAGTAIL_AUTOSAVE_INTERVAL = 0

# If true, the preview panel in the page editor is automatically updated on each change.
# If false, the preview panel is only updated when the refresh button is clicked.
WAGTAIL_AUTO_UPDATE_PREVIEW = False

# Allowed file extensions for documents in the document library.
# This can be omitted to allow all files, but note that this may present a security risk
# if untrusted users are allowed to upload files -
# see https://docs.wagtail.org/en/stable/advanced_topics/deploying.html#user-uploaded-files
WAGTAILDOCS_EXTENSIONS = [
    'csv', 'docx', 'key', 'odt', 'pdf', 'pptx', 'rtf', 'txt', 'xlsx', 'zip',
]

WAGTAILIMAGES_MAX_UPLOAD_SIZE = 10 * 1024 * 1024  # 10MB

# see https://github.com/torchbox/wagtailmedia
WAGTAILMEDIA = {
    "AUDIO_EXTENSIONS": [
        "aac", "aiff", "flac", "m4a", "m4b", "mp3", "ogg", "wav",
    ],
    "VIDEO_EXTENSIONS": [
        "avi", "h264", "m4v", "mkv", "mov", "mp4", "mpeg", "mpg", "ogv", "webm",
    ],
}

TAGGIT_CASE_INSENSITIVE = False
WAGTAIL_TAG_SPACES_ALLOWED = False

WAGTAIL_WORKFLOW_ENABLED = True
WAGTAIL_WORKFLOW_REQUIRE_REAPPROVAL_ON_EDIT = False

# Front-end cache invalidation
# https://docs.wagtail.org/en/stable/reference/contrib/frontendcache.html
CLOUDFLARE_EMAIL   = config.get('wagtail', 'cloudflare_email'),
CLOUDFLARE_API_KEY = config.get('wagtail', 'cloudflare_api_key'),
CLOUDFLARE_ZONEID  = config.get('wagtail', 'cloudflare_zoneid'),
if CLOUDFLARE_EMAIL and CLOUDFLARE_API_KEY and CLOUDFLARE_ZONEID:
    INSTALLED_APPS += ['wagtail.contrib.frontend_cache']
    WAGTAILFRONTENDCACHE = {
        'public': {
            'BACKEND': 'wagtail.contrib.frontend_cache.backends.CloudflareBackend',
            'EMAIL': CLOUDFLARE_EMAIL,
            'API_KEY': CLOUDFLARE_API_KEY,
            'ZONEID': CLOUDFLARE_ZONEID,
            'HOSTNAMES': ['encyclopedia.densho.org']
        },
        'editors2': {
            'BACKEND': 'wagtail.contrib.frontend_cache.backends.CloudflareBackend',
            'EMAIL': CLOUDFLARE_EMAIL,
            'API_KEY': CLOUDFLARE_API_KEY,
            'ZONEID': CLOUDFLARE_ZONEID,
            'HOSTNAMES': ['editors2.densho.org']
        },
}

# django-pattern-library
if DEBUG:
    X_FRAME_OPTIONS = "SAMEORIGIN"
PATTERN_LIBRARY = {
    # Groups of templates for the pattern library navigation. The keys
    # are the group titles and the values are lists of template name prefixes that will
    # be searched to populate the groups.
    "SECTIONS": (
        ("styleguide", ["patterns/styleguide"]),
        ("components", ["patterns/components"]),
        ("pages", ["patterns/pages"]),
        ("sprites", ["patterns/sprites"]),
    ),

    # Configure which files to detect as templates.
    "TEMPLATE_SUFFIX": ".html",

    # Set which template components should be rendered inside of,
    # so they may use page-level component dependencies like CSS.
    "PATTERN_BASE_TEMPLATE_NAME": "patterns/base.html",

    # Any template in BASE_TEMPLATE_NAMES or any template that extends a template in
    # BASE_TEMPLATE_NAMES is a "page" and will be rendered as-is without being wrapped.
    "BASE_TEMPLATE_NAMES": ["patterns/base_page.html"],
}


# encyc-tng

PAGINATION_MAX_PER_PAGE_SIZE = 100  # django-ninja

ENCYC_TOPICS_PATH = config.get('encyctng', 'encyc_topics_path').strip()
DDR_VOCAB_TOPICS_PATH = config.get('encyctng', 'vocab_topics_path').strip()

GITPKG_DEBUG = config.getboolean('encyctng', 'gitpkg_debug')
if GITPKG_DEBUG:
    # report Git branch and commit
    # This branch is the one with the leading '* '.
    #try:
    GIT_BRANCH = [
        b.decode().replace('*','').strip()
        for b in subprocess.check_output(['git', 'branch']).splitlines()
        if '*' in b.decode()
       ][0]

    GIT_COMMIT = subprocess.check_output([
        'git', 'log', '--pretty=format:%H %d %ad', '--date=iso', '-1'
    ]).decode().replace('  ', ' ')

    def package_debs(package, apt_cache_dir='/var/cache/apt/archives'):
        """
        @param package: str Package name
        @param apt_cache_dir: str Absolute path
        @returns: list of .deb files matching package and version
        """
        cmd = 'dpkg --status %s' % package
        try:
            dpkg_raw = subprocess.check_output(cmd.split(' ')).decode()
        except subprocess.CalledProcessError:
            return ''
        data = {}
        for line in dpkg_raw.splitlines():
            if line and isinstance(line, str) and (':' in line):
                key,val = line.split(':', 1)
                data[key.strip().lower()] = val.strip()
        pkg_paths = [
            path for path in os.listdir(apt_cache_dir)
            if (package in path) and data.get('version') and (data['version'] in path)
        ]
        return pkg_paths

    PACKAGES = package_debs('encyctng-%s' % GIT_BRANCH)

else:
    GIT_COMMIT = ''
    GIT_BRANCH = ''
    PACKAGES = 'PACKAGES'
