# Generated by Django 5.2.8 on 2025-11-25 19:48

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.fields.StreamField([('paragraph', 0)], block_lookup={0: ('info.blocks.ArticleTextBlock', (), {})}, help_text='Description should only be one paragraph.')),
                ('body', wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('quote', 6), ('imageblock', 11), ('videoblock', 14), ('documentblock', 16)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('', 'Select a heading size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 1)]], {}), 3: ('info.blocks.ArticleTextBlock', (), {}), 4: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('quotation', 4), ('attribution', 5)]], {}), 7: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 8: ('wagtail.images.blocks.ImageBlock', [], {}), 9: ('wagtail.blocks.TextBlock', (), {'required': False}), 10: ('wagtail.blocks.URLBlock', (), {'required': False}), 11: ('wagtail.blocks.StructBlock', [[('signature', 7), ('image', 8), ('caption', 9), ('caption2', 9), ('courtesy', 5), ('creative_commons', 7), ('ext_url', 10)]], {}), 12: ('wagtailmedia.blocks.VideoChooserBlock', (), {'required': False}), 13: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': False}), 14: ('wagtail.blocks.StructBlock', [[('video', 12), ('display', 8), ('transcript', 13), ('caption', 9), ('caption2', 9), ('courtesy', 5), ('creative_commons', 7)]], {}), 15: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': True}), 16: ('wagtail.blocks.StructBlock', [[('document', 15), ('display', 8), ('caption', 9), ('caption2', 9), ('courtesy', 5), ('creative_commons', 7), ('ext_url', 10)]], {})}, help_text='BODY HELP TEXT GOES HERE.')),
            ],
            options={
                'verbose_name': 'Site Article',
                'verbose_name_plural': 'Site Articles',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SitePagesIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
